########################################################################################
# <컨테이너목록>
# * 아래의 모든 컨테이너들을 일괄로 생성한다.
# 1. dstone-mysql(데이터베이스)
# 2. dstone-rabbitmq(RabbitMQ)
# 3. dstone-redis(Redis)
# 4. dstone-boot(Application 프레임웍)
# 
# <사전작업>
# 1. 작업디렉토리 결정 후 템플릿 복사.
#   /workshop
# 
# <작업명령>
# 1. Docker Compose 실행
#   - docker-compose -p dstone -f /workshop/dstone-batch-docker-compose.yml up -d
# 2. 로그 확인
#   - docker-compose -p dstone -f /workshop/dstone-batch-docker-compose.yml logs -f
# 3. 중지 및 삭제
#   - docker-compose -p dstone -f /workshop/dstone-batch-docker-compose.yml down -v
########################################################################################
services:
  
  # MySQL 데이터베이스 서버
  dstone-mysql:  
    # ---------- 최초작업일 때 ---------------------- #
    # image: mysql:8.0
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    image: jysn007/dstone-mysql:latest
    # --------------------------------------------- #    
    container_name: dstone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: db2admin!@
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_0900_ai_ci
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dstone-mysql/init-db:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    networks:
      - dstone-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ 서버
  dstone-rabbitmq:    
    # ---------- 최초작업일 때 ---------------------- #
    # image: rabbitmq:3.13-management
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    image: jysn007/dstone-rabbitmq:latest
    # --------------------------------------------- #    
    container_name: dstone-rabbitmq
    hostname: dstone-rabbitmq
    ports:
      - "5672:5672"   # AMQP 프로토콜 포트
      - "15672:15672" # Management UI 포트
    environment:
      ###########################################################  
      # RABBITMQ_DEFAULT_USER/PASS/VHOST 와 RABBITMQ_LOAD_DEFINITIONS안에 
      # 동일한 사용자/브이호스트가 있으면 definitions 로딩이 스킵될 수 있음.
      # 따라서 RABBITMQ_LOAD_DEFINITIONS을 쓸 경우 RABBITMQ_DEFAULT_USER/PASS/VHOST 제거.
      ###########################################################  
      #RABBITMQ_DEFAULT_USER: jysn007
      #RABBITMQ_DEFAULT_PASS: db2admin!@
      #RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
      - ./dstone-rabbitmq/init-data/dstone-rabbitmq_data.json:/etc/rabbitmq/definitions.json:ro
      # 설정 파일 마운트
      - ./dstone-rabbitmq/init-data/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - dstone-network
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      
  # Redis 서버
  dstone-redis:    
    # ---------- 최초작업일 때 ---------------------- #
    # image: redis:7.2
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    image: jysn007/dstone-redis:latest
    # --------------------------------------------- #    
    container_name: dstone-redis
    hostname: dstone-redis
    ports:
      - "6379:6379"   # Redis 기본 포트
    ulimits:
      nofile:
        soft: 10032
        hard: 10032
    command: ["redis-server", "--protected-mode", "no"] 
    volumes:
      - redis_data:/data
    networks:
      - dstone-network
    restart: unless-stopped
      
  # Application 프레임웍 
  dstone-boot:
    # ---------- 최초작업일 때 ---------------------- #
    # image: eclipse-temurin:21-jdk
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    image: jysn007/dstone-boot:latest
    # --------------------------------------------- #    
    container_name: dstone-boot
    ports:
      - "7081:7081"
    volumes:
      - /workshop/dstone-boot/target/dstone-boot.war:/workshop/dstone-boot/target/dstone-boot.war
      - /workshop/dstone-boot/conf:/workshop/dstone-boot/conf
    networks:
      - dstone-network
    depends_on:
      - dstone-mysql
      - dstone-rabbitmq
      - dstone-redis
    command:
      - /bin/bash
      - -c
      - |
        echo "Starting Spring Boot Application..."
        java -Xms512m -Xmx1024m -Dspring.profiles.active=dev -jar /workshop/dstone-boot/target/dstone-boot.war net.dstone.DstoneBootApplication
    restart: unless-stopped
    #restart: "no"

networks:
  dstone-network:
    driver: bridge

volumes:
  # MySQL 볼륨
  mysql-data:
  # RabbitMQ 볼륨
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  # Redis 볼륨
  redis_data:
    driver: local