########################################################################################
# <사전작업>
# 1. 호스트 작업디렉토리 결정 후 템플릿 복사.
#   /workshop/dstone-mysql
# <작업명령>
# 1. Docker Compose 실행
#   - docker-compose -p dstone -f /workshop/dstone-mysql/01.dstone-mysql-docker.yml up -d
# 2. 로그 확인
#   - docker-compose -p dstone -f /workshop/dstone-mysql/01.dstone-mysql-docker.yml logs -f dstone-mysql
# 3. 중지 및 삭제
#   - docker-compose -p dstone -f /workshop/dstone-mysql/01.dstone-mysql-docker.yml down -v
########################################################################################
services:

  # MySQL 데이터베이스 서버
  dstone-mysql:
  
    # ---------- 최초작업일 때 ---------------------- #
    image: mysql:8.0
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    # image: jysn007/dstone-mysql:latest
    # --------------------------------------------- #
    
    container_name: dstone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: db2admin!@
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_0900_ai_ci
    ports:
      - "33060:3306"
      
    ###########################################################  
    # 서비스 내부 Volumes (바인드 마운트 vs 볼륨 참조)
    # A.타입 1: 바인드 마운트 (Bind Mount)
    #   - 호스트의 실제 경로를 컨테이너에 연결
    #   - 경로가 .로 시작하거나 /로 시작 (절대경로)
    #   - 파일이나 디렉토리를 직접 공유
    #   - 용도: 코드, 설정 파일 등 자주 수정하는 것들
    #   예) - ./backend:/app
    # B.타입 2: 네임드 볼륨 참조 (Named Volume)
    #   - Docker가 관리하는 볼륨을 컨테이너에 연결
    #   - 이름만 적음 (경로 없음)
    #   - 실제 저장 위치는 Docker가 관리(보통 호스트의 /var/lib/docker/volumes/<프로젝트명>_<볼륨명>/_data 디렉토리)
    #   - 최하단 Volumes 선언(볼륨 정의)이 되어있어야 함.
    #   - 용도: 데이터베이스 데이터처럼 영구 보존이 필요하지만 직접 수정할 일은 없는 것들
    #   예) - db-data:/var/lib/postgresql/data
    #      호스트위치 : /var/lib/docker/volumes/mysql_db-data/_data
    #      컨테이너위치 : /var/lib/postgresql/data
    ###########################################################     
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    networks:
      - dstone-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  dstone-network:
    driver: bridge
    
######################################
# Volumes 선언(볼륨 정의)
# - 네임드 볼륨 참조 (Named Volume)에서 사용.
######################################
volumes:
  # MySQL 볼륨
  mysql-data: